// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntcdjpzrrzzadlqoaiks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Y2RqcHpycnp6YWRscW9haWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzQ3MjEsImV4cCI6MjA1NTgxMDcyMX0.rYJ6Wy9kQDXR3iDtqObChd9xhOPmH41lRa3Ch-cMa30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);